### ISSUE TITLE
Challenge no longer works

### ISSUE THREAD

**Issue by mickoner** [dschioberg/MIDSbasics#1]
In MIDS-1D-Computing-Basics.md the challenge link is not working:

![image](https://user-images.githubusercontent.com/702573/125871507-cfe65ad4-240b-4671-8d62-5f75259f6e2b.png)

**Comment by dschioberg** [comment]
Thank you for letting me know! We're working on a fix. In the meantime please use this link to see the challenge:
https://docs.google.com/document/d/1ENcEp9UpTUxbU5GDlXn5stMt1hlHqDupNAwcBrcdmuQ/edit?usp=sharing
Afterwards please invite me to your repo with the solution, GitHub ID dschioberg
